version: '3.8'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workfly
    ports:
      - '5432:5432'